server.port: 80

spring:
  threads.virtual.enabled: true
  config:
    import:
      - classpath:/config/career-en.yml
      - classpath:/config/career-nl.yml
      - classpath:/config/recommendations.yml
