server.port: 80

spring:
  threads.virtual.enabled: true
  config:
    import:
      - classpath:/config/career-en.yml
      - classpath:/config/career-nl.yml
      - classpath:/config/recommendations.yml
  web:
    resources:
      cache:
        period: 365d
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  jackson:
    default-property-inclusion: non_null
